version: 2
updates:
  - directories:
      - '*/internal'
    open-pull-requests-limit: 5
    package-ecosystem: terraform
    schedule:
      interval: weekly
  - directories:
      - .
    open-pull-requests-limit: 3
    package-ecosystem: gomod
    schedule:
      interval: monthly
