name: autorelease
"on":
  schedule:
    - cron: 0 10 20 * *
  workflow_dispatch: {}
jobs:
  release:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GENERATOR_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25"
      - name: Set up CUE
        run: go install cuelang.org/go/cmd/cue
      - name: Login to CUE Registry
        uses: cue-labs/registry-login-action@v1
      - name: Execute
        run: |-
          git config user.name "cuetf generator (bot)"
          git config user.email "cuetf-bot@rmazur.io"
          branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          git checkout "origin/$branch"
          go run ./internal/cmd/monthly-release
