name: regenerate
"on":
  pull_request:
    branches:
      - main
    types:
      - labeled
jobs:
  regenerate:
    if: startsWith(github.event.label.name, 'provider:')
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GENERATOR_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25"
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.4
      - name: Set up CUE
        run: go install cuelang.org/go/cmd/cue
      - name: Execute
        run: |-
          git config user.name "cuetf generator (bot)"
          git config user.email "cuetf-bot@rmazur.io"
          branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          git checkout "origin/$branch"
          export label="${{ github.event.label.name }}"
          export provider=${label#"provider:"}
          echo "Regenerating for $provider"
          ./update-providers.sh "$provider"

          git add "$provider"
          git add "logs/$provider-log.txt"
          git commit -m "$provider: regenerate on dep update"
          git push origin HEAD:"$branch"

          echo "Setting the PR to merge after all checks"
          sleep 10
          gh pr merge --auto --merge "${{ github.event.pull_request.html_url }}"
        env:
          GH_TOKEN: ${{ secrets.GENERATOR_TOKEN }}
